name: Latest blog post workflow

on:
  schedule:
    - cron: "0 1 * * *" # 毎日10:00(JST)に自動実行
  workflow_dispatch: # GitHub Actions画面から手動実行可能

jobs:
  update-readme-with-blog:
    name: Update README with latest Zenn posts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zenn.dev/maton369/feed"
