name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Force Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git reset --hard origin/main
          git add -A
          git diff-index --quiet HEAD || git commit -m "generated"
          git push origin main --force
